# version: '3'
# services:
#   influxdb:
#     image: "influxdb:1.8"
#     volumes:
#       - ./data/influxdb:/var/lib/influxdb
#     ports:
#      - "8086:8086"
#     restart: always
#     environment:
#      - INFLUXDB_DB="telegraf"

#   telegraf:
#     image: "telegraf"
#     volumes:
#       - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
#     ports:
#       - "8092:8092/udp"
#       - "8094:8094"
#       - "8125:8125/udp"
#       - "6514:514/udp"
#     restart: always
#     extra_hosts:
#       - "router:192.168.30.1"
#     depends_on:
#       - influxdb

#   grafana:
#     image: grafana/grafana-oss
#     volumes:
#        - grafana-data:/var/lib/grafana
#        - ./dashboards:/etc/grafana/provisioning/dashboards
#     ports:
#       - "3000:3000"
#     restart: always
#     environment:
#       - GF_INSTALL_PLUGINS=natel-plotly-panel,grafana-simple-json-datasource,natel-discrete-panel
#     depends_on:
#       - influxdb

# volumes:
#  grafana-data:


version: '3'
services:
  influxdb:
    image: "influxdb:1.8"
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
    restart: always
    environment:
      - INFLUXDB_DB="telegraf"
    networks:
      - monitoring-network

  telegraf:
    image: "telegraf"
    volumes:
      - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
      - "6514:514/udp"
    restart: always
    extra_hosts:
      - "router:192.168.20.1"
    depends_on:
      - influxdb
    networks:
      - monitoring-network

  grafana:
    image: grafana/grafana-oss
    volumes:
      - grafana-data:/var/lib/grafana
      - ./dashboards:/etc/grafana/provisioning/dashboards
      - ./datasources:/etc/grafana/provisioning/datasources
    ports:
      - "3000:3000"
    restart: always
    environment:
      - GF_INSTALL_PLUGINS=natel-plotly-panel,grafana-simple-json-datasource,natel-discrete-panel
    depends_on:
      - influxdb
    networks:
      - monitoring-network
volumes:
  grafana-data:
networks:
  monitoring-network:
    driver: bridge