{
 "title": "Network",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "MAIN_ROUTER",
    "label": "Main Router Hostaname",
    "query": {
     "query": "SHOW TAG VALUES FROM \"ntwrk_system\" WITH KEY = \"sysName\""
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime [RB760iGS]",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "ntwrk_system",
     "query": "SELECT last(\"uptime\")  / 100 FROM ntwrk_system WHERE \"sysName\" =~ /^$MAIN_ROUTER$/  AND $timeFilter\n\n",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sysName", "operator": "=~", "value": "/^$MAIN_ROUTER$/" }
     ]
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "ntwrk_system",
     "query": "SELECT \"voltage\" /10 FROM ntwrk_system WHERE  \"sysName\" =~ /^$MAIN_ROUTER$/  AND $timeFilter",
     "select": [
      [
       { "params": [ "voltage" ], "type": "field" },
       { "params": [ "/10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sysName", "operator": "=~", "value": "/^$MAIN_ROUTER$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "ntwrk_system",
     "query": "SELECT \"temperature\"  FROM ntwrk_system WHERE \"sysName\" =~ /^$MAIN_ROUTER$/  AND $timeFilter",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       { "params": [ "/10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sysName", "operator": "=~", "value": "/^$MAIN_ROUTER$/" }
     ]
    }
   ]
  },
  {
   "title": "DHCP Leases",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "ntwrk_system",
     "query": "SELECT mtxrDHCPLeaseCount FROM ntwrk_system WHERE \"sysName\" =~ /^$MAIN_ROUTER$/  AND $timeFilter\n",
     "select": [
      [
       { "params": [ "mtxrDHCPLeaseCount" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sysName", "operator": "=~", "value": "/^$MAIN_ROUTER$/" }
     ]
    }
   ]
  },
  {
   "title": "Interface Status",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_ifName",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "ntwrk_interfaces",
     "query": "SELECT mean(\"ifOperStatus\") FROM \"ntwrk_interfaces\" WHERE (\"sysName\" =~ /^$MAIN_ROUTER$/) AND $timeFilter GROUP BY time(1m), \"ifName\" fill(previous)",
     "select": [
      [
       { "params": [ "ifOperStatus" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sysName", "operator": "=~", "value": "/^$MAIN_ROUTER$/" }
     ]
    }
   ]
  },
  {
   "title": "Syslog",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "query": "SELECT \"message\", \"host\", \"severity\", \"time\"\nFROM \"syslog\"\nWHERE \"appname\" = 'CRON' AND \"facility\" = 'authpriv' AND $timeFilter\nORDER BY time DESC\n"
    }
   ]
  },
  {
   "title": "LAN activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "alias": "$tag_ifName.$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifName" ], "type": "tag" }
     ],
     "measurement": "ntwrk_interfaces",
     "query": "SELECT non_negative_derivative(mean(\"ifInOctets\"), 1s) AS \"recv\", non_negative_derivative(mean(\"ifOutOctets\"), 1s) *(-1) AS \"sent\" FROM \"ntwrk_interfaces\" WHERE (\"ifName\" =~ /^ether*/ AND \"sysName\" =~ /^$MAIN_ROUTER$/) AND $timeFilter GROUP BY time($__interval), \"ifName\"",
     "select": [
      [
       { "params": [ "ifInOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "recv" ], "type": "alias" }
      ],
      [
       { "params": [ "ifOutOctets" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*(-1)" ], "type": "math" },
       { "params": [ "sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "ifName", "operator": "=~", "value": "/^ether*/" },
      { "condition": "AND", "key": "sysName", "operator": "=~", "value": "/^$MAIN_ROUTER$/" }
     ]
    }
   ]
  },
  {
   "title": "Ping response",
   "type": "heatmap",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Packet loss",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Ping to $tag_url",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "query": "SELECT mean(\"percent_packet_loss\") FROM \"ping\" WHERE $timeFilter GROUP BY time(1m), \"url\" fill(null)",
     "select": [
      [
       { "params": [ "percent_packet_loss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DNS resolver",
   "type": "heatmap",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dns_query",
     "query": "SELECT mean(\"query_time_ms\") FROM \"dns_query\" WHERE $timeFilter GROUP BY time(5m), \"server\" fill(null)",
     "select": [
      [
       { "params": [ "query_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ping query time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Ping to $tag_url",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "query": "SELECT mean(\"average_response_ms\") FROM \"ping\" WHERE $timeFilter GROUP BY time(1m), \"url\" fill(null)",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DNS Resolve (query time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Query to $tag_server",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dns_query",
     "query": "SELECT mean(\"query_time_ms\") FROM \"dns_query\" WHERE $timeFilter GROUP BY time(1m), \"server\" fill(null)",
     "select": [
      [
       { "params": [ "query_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}